name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l  # ensures conda env activation works

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ⚡ Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          environment-name: test-env
          cache-environment: true
          init-shell: bash

      - name: 📦 Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: 🛠️ Install Python dependencies with Poetry
        run: |
          poetry install

      - name: ✅ Run tests with pytest
        run: |
          poetry run pytest
